{% set version = "4.1.5" %}
{% set ver_maj_min_str = "-".join(version.split(".")[:2]) %}

package:
  name: zeromq
  version: {{ version }}

source:
  fn: zeromq-{{ version }}.tar.gz
  url: https://github.com/zeromq/zeromq4-1/archive/v{{ version }}.tar.gz
  sha256: 5a993dcc330e63610fd74a6701b83b020aa5aedf22a98fea01eac93c72ff0b78

build:
  number: 0

requirements:
  build:
    - toolchain
    - automake    # [unix]
    - autoconf    # [unix]
    - libtool     # [unix]
    - pkg-config  # [unix]
    - libsodium   # [unix]

  run:
    - libsodium   # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a           # [unix]
    - test -f ${PREFIX}/lib/libzmq.dylib       # [osx]
    - test -f ${PREFIX}/lib/libzmq.so          # [linux]

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
